trigger:
- main   # this runs the pipeline whenever there is a commit to main branch

pool:
  name: Default   # your agent pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
